/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Editora;
import model.Livro;
import services.EditoraServicos;
import services.LivroServicos;
import services.ServicosFactory;

/**
 *
 * @author sarin
 */
public class jfLivro extends javax.swing.JFrame {

    /**
     * Creates new form jfLivro
     */
    public jfLivro() {
        initComponents();
        addRowToTable();
        jbLivroDeletar.setVisible(false);
        this.setLocationRelativeTo(null);//Para centralizar a janela
    }

    public boolean validaInputs() {
        if (jtfTitulo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher título!");
            jtfTitulo.requestFocus();
            return false;
        } else if (jtfAutor.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher autor!");
            jtfAutor.requestFocus();
            return false;
        } else if (jtfAssunto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher assunto!");
            jtfAssunto.requestFocus();
            return false;
        } else if (jtfISBN.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher ISBN!");
            jtfISBN.requestFocus();
            return false;
        } else if (jtfEstoque.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher estoque!");
            jtfEstoque.requestFocus();
            return false;
        } else if (jtfPreco.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher estoque!");
            jtfPreco.requestFocus();
            return false;
        } else if (jtfCNPJ.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher editora!");
            jtfCNPJ.requestFocus();
            return false;
        }
        return true;
    }//fim validaInputs

    public void addRowToTable() {//Pegar o model limpar essa tabela e popular a mesma, se não fizer isso ela fica estática.
        DefaultTableModel model = (DefaultTableModel) jtLivros.getModel();
        model.getDataVector().removeAllElements();//Remove todas as linhas.
        model.fireTableDataChanged();
        Object rowData[] = new Object[7];//rowData é o vetor para popular a linha da tabela por coluna
        LivroServicos livroS = ServicosFactory.getLivroServicos();
        for (Livro li : livroS.buscaLivros()) {//O vetor sempre começa em 0
            rowData[0] = li.getTitulo();
            rowData[1] = li.getAutor();
            rowData[2] = li.getAssunto();
            rowData[3] = li.getIsbn();
            rowData[4] = li.getEstoque();
            rowData[5] = li.getPreco();
            rowData[6] = li.getIdEditora().getNomeEditora();
            model.addRow(rowData);//Add para popular.
        }
    }

    public void somenteNum(java.awt.event.KeyEvent evt) {
        String number = "0123456789";
        if (jtfISBN.getText().length() < 13) {
            if (!number.contains(evt.getKeyChar() + "")) {//evento(evt) a tecla que foi teclada.
                evt.consume();
            }
        } else {
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void jbLivroLimpar(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (jbLivroLimpar.getText().equals("Limpar")) {
            limparCampos();
        } else {
            limparCampos();
            jbLivroLimpar.setText("Limpar");
            jbLivroSalvar.setText("Salvar");
            jbLivroEditar.setEnabled(false);
            jtfISBN.setEnabled(true);
            jbLivroDeletar.setVisible(false);
        }
    }

    public void limparCampos() {
        jtfTitulo.setText("");
        jtfAutor.setText("");
        jtfAssunto.setText("");
        jtfISBN.setText("");
        jtfEstoque.setText("");
        jtfPreco.setText("");
        jtfCNPJ.setText("");
        jtfTitulo.requestFocus();
    }

    private void jtLivros(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jbLivroEditar.setEnabled(true);
        jbLivroDeletar.setVisible(true);
    }

    private void jbLivroFechar(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }

    private void jbEditEditar(java.awt.event.ActionEvent evt) {
        //ActionPerformed ação de clicar
        jbLivroSalvar.setText("Confirmar");
        jtfISBN.setEnabled(false);
        jtfCNPJ.setEnabled(false);
        jbLivroLimpar.setText("Cancelar");
        jbLivroDeletar.setVisible(false);

        //Pegando dados da tabela e add em variaveis locais.
        int linha;
        linha = jtLivros.getSelectedRow();
        String isbn = (String) jtLivros.getValueAt(linha, 3);
        LivroServicos livroS = ServicosFactory.getLivroServicos();
        Livro li = livroS.buscaLivroISBN(isbn);
        //Carregar dados da tabela no form
        jtfTitulo.setText(li.getTitulo());
        jtfAutor.setText(li.getAutor());
        jtfAssunto.setText(li.getAssunto());
        jtfISBN.setText(li.getIsbn());
        jtfEstoque.setText(String.valueOf(li.getEstoque()));
        jtfPreco.setText(String.valueOf(li.getPreco()));
        jtfCNPJ.setText(li.getIdEditora().getCnpj());
        jtfTitulo.requestFocus();
    }

    private void jbEditDeletar(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int linha;
        String cnpj;
        linha = jtLivros.getSelectedRow();
        cnpj = (String) jtLivros.getValueAt(linha, 0);
        LivroServicos livroS = ServicosFactory.getLivroServicos();
        Object[] resp = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(this, "Deseja realmente deletar este CNPJ? ", "Deletar", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, resp, resp[0]);
        if (resposta == 0) {
            livroS.deletarLivro(cnpj);
            addRowToTable();
            JOptionPane.showMessageDialog(this, "Livro deletado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Ok, entendo sua descisão!");
        }
        jbLivroDeletar.setVisible(false);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jtfAssunto = new javax.swing.JTextField();
        jtfAutor = new javax.swing.JTextField();
        jtfTitulo = new javax.swing.JTextField();
        jtfISBN = new javax.swing.JTextField();
        jtfEstoque = new javax.swing.JTextField();
        jtfPreco = new javax.swing.JTextField();
        jtfCNPJ = new javax.swing.JTextField();
        jbLivroLimpar = new javax.swing.JButton();
        jbLivroEditar = new javax.swing.JButton();
        jbLivroFechar = new javax.swing.JButton();
        jbLivroSalvar = new javax.swing.JButton();
        jbLivroDeletar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLivros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerência Livro");

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerência Livro");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("*Titulo:");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("*Autor:");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("*Assunto:");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("*ISBN:");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("*Estoque:");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("*Preço:");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("*Editora:");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jtfAssunto.setBackground(new java.awt.Color(255, 255, 255));
        jtfAssunto.setToolTipText("Informe o assunto do livro");
        jtfAssunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAssuntoKeyTyped(evt);
            }
        });

        jtfAutor.setBackground(new java.awt.Color(255, 255, 255));
        jtfAutor.setToolTipText("Informe o autor do livro");
        jtfAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAutorKeyTyped(evt);
            }
        });

        jtfTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jtfTitulo.setToolTipText("Informe o título do livro");
        jtfTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTituloKeyTyped(evt);
            }
        });

        jtfISBN.setBackground(new java.awt.Color(255, 255, 255));
        jtfISBN.setToolTipText("Informe o registro ISBN ");
        jtfISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfISBNKeyTyped(evt);
            }
        });

        jtfEstoque.setBackground(new java.awt.Color(255, 255, 255));
        jtfEstoque.setToolTipText("Informe o número de livros no estoque");

        jtfPreco.setBackground(new java.awt.Color(255, 255, 255));
        jtfPreco.setToolTipText("Informe o preço do livro");

        jtfCNPJ.setBackground(new java.awt.Color(255, 255, 255));
        jtfCNPJ.setToolTipText("Informe o CNPJ da editora");
        jtfCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCNPJFocusLost(evt);
            }
        });

        jbLivroLimpar.setBackground(new java.awt.Color(255, 255, 255));
        jbLivroLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLivroLimpar.setForeground(new java.awt.Color(0, 0, 0));
        jbLivroLimpar.setText("Limpar");
        jbLivroLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLivroLimparActionPerformed(evt);
            }
        });

        jbLivroEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbLivroEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLivroEditar.setForeground(new java.awt.Color(0, 0, 0));
        jbLivroEditar.setText("Editar");
        jbLivroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLivroEditarActionPerformed(evt);
            }
        });

        jbLivroFechar.setBackground(new java.awt.Color(255, 255, 255));
        jbLivroFechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLivroFechar.setForeground(new java.awt.Color(0, 0, 0));
        jbLivroFechar.setText("Fechar");
        jbLivroFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLivroFecharActionPerformed(evt);
            }
        });

        jbLivroSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jbLivroSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLivroSalvar.setForeground(new java.awt.Color(0, 0, 0));
        jbLivroSalvar.setText("Salvar");
        jbLivroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLivroSalvarActionPerformed(evt);
            }
        });

        jbLivroDeletar.setBackground(new java.awt.Color(255, 255, 255));
        jbLivroDeletar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLivroDeletar.setForeground(new java.awt.Color(0, 0, 0));
        jbLivroDeletar.setText("Deletar");
        jbLivroDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLivroDeletarActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jtLivros.setBackground(new java.awt.Color(255, 255, 255));
        jtLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Assunto", "ISBN", "Estoque", "Preço", "Editora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtLivros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAssunto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtfAutor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(23, 23, 23)
                        .addComponent(jtfISBN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCNPJ))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEstoque)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbLivroLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLivroEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbLivroDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLivroSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLivroFechar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jtfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLivroLimpar)
                    .addComponent(jbLivroEditar)
                    .addComponent(jbLivroFechar)
                    .addComponent(jbLivroSalvar)
                    .addComponent(jbLivroDeletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfISBNKeyTyped
        // TODO add your handling code here:
        somenteNum(evt);
    }//GEN-LAST:event_jtfISBNKeyTyped

    private void jtfCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCNPJFocusLost
        // TODO add your handling code here:
        EditoraServicos editS = ServicosFactory.getEditoraServicos();
        Editora edit = editS.buscarEditorabyCNPJ(jtfCNPJ.getText());
        if (edit.getCnpj() == null) {
            JOptionPane.showMessageDialog(this, "Editora não cadastrada!", "Pesquisa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object[] resp = {"Sim", "Não"};
            int resposta = JOptionPane.showOptionDialog(this, "Editora " + edit.getNomeEditora() + " está correta? ", "Pesquisa", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, resp, resp[0]);
            if (resposta == 1) {
                jtfCNPJ.setText("");
                jtfCNPJ.requestFocus();
            }
        }
    }//GEN-LAST:event_jtfCNPJFocusLost

    private void jtfTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTituloKeyTyped
        // TODO add your handling code here:
        String nletras = "0123456789<>:?/~^}][{´`=+-_!|'\'@#$%¨&*()²³£¢¬§º°ª";
        if (nletras.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfTituloKeyTyped

    private void jbLivroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLivroSalvarActionPerformed
        // TODO add your handling code here:
        if (validaInputs()) {
            //Pegar dados da tela para salvar
            int idLivro = 0;
            String titulo = jtfTitulo.getText().toUpperCase();
            String autor = jtfAutor.getText().toUpperCase();
            String assunto = jtfAssunto.getText().toUpperCase();
            String isbn = jtfISBN.getText();
            int estoque = Integer.parseInt(jtfEstoque.getText());
            float preco = Float.parseFloat(jtfPreco.getText());
            EditoraServicos editS = ServicosFactory.getEditoraServicos();
            Editora edit = editS.buscarEditorabyCNPJ(jtfCNPJ.getText());
            LivroServicos livroS = ServicosFactory.getLivroServicos();

            Livro li = new Livro(idLivro, titulo, autor, assunto, isbn, estoque, preco, edit);
            if (jbLivroSalvar.getText().equals("Salvar")) {
                livroS.cadLivro(li);
            } else {
                livroS.atualizarLivro(li);
                jbLivroLimpar.doClick();
            }
            limparCampos();
            addRowToTable();
        }
    }//GEN-LAST:event_jbLivroSalvarActionPerformed

    private void jtfAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAutorKeyTyped
        // TODO add your handling code here:
        String nletras = "0123456789<>:?/~^}][{´`=+-_!|'\'@#$%¨&*()²³£¢¬§º°ª";
        if (nletras.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfAutorKeyTyped

    private void jtfAssuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAssuntoKeyTyped
        // TODO add your handling code here:
        String nletras = "0123456789<>:?/~^}][{´`=+-_!|'\'@#$%¨&*()²³£¢¬§º°ª";
        if (nletras.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfAssuntoKeyTyped

    private void jbLivroLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLivroLimparActionPerformed
        // TODO add your handling code here:
        jbLivroLimpar(evt);
    }//GEN-LAST:event_jbLivroLimparActionPerformed

    private void jbLivroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLivroEditarActionPerformed
        // TODO add your handling code here:
        jbEditEditar(evt);
    }//GEN-LAST:event_jbLivroEditarActionPerformed

    private void jbLivroDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLivroDeletarActionPerformed
        // TODO add your handling code here:
        jbEditDeletar(evt);
    }//GEN-LAST:event_jbLivroDeletarActionPerformed

    private void jbLivroFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLivroFecharActionPerformed
        // TODO add your handling code here:
        jbLivroFechar(evt);
    }//GEN-LAST:event_jbLivroFecharActionPerformed

    private void jtLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLivrosMouseClicked
        // TODO add your handling code here:
        jtLivros(evt);
    }//GEN-LAST:event_jtLivrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbLivroDeletar;
    private javax.swing.JButton jbLivroEditar;
    private javax.swing.JButton jbLivroFechar;
    private javax.swing.JButton jbLivroLimpar;
    private javax.swing.JButton jbLivroSalvar;
    private javax.swing.JTable jtLivros;
    private javax.swing.JTextField jtfAssunto;
    private javax.swing.JTextField jtfAutor;
    private javax.swing.JTextField jtfCNPJ;
    private javax.swing.JTextField jtfEstoque;
    private javax.swing.JTextField jtfISBN;
    private javax.swing.JTextField jtfPreco;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables
}
